// nullrpc-executor: EVM execution and tracing (revm in WebAssembly, crate/) for every chain's
// RPC Worker, reached only through service bindings to the `Executor` entrypoint.

import { WorkerEntrypoint } from "cloudflare:workers";
import type { ExecRequest, ExecResponse, ExecutorApi, StateSource } from "./contract";
import { EXECUTOR_METHODS } from "./contract";
import { execute, type WasmSession } from "./shell";
// Generated by scripts/build.sh (wrangler's build command) into crate/pkg.
// @ts-ignore -- generated JavaScript without type declarations
import { __nullrpc_reset, initSync, Session } from "../crate/pkg/executor.js";
// @ts-ignore -- a compiled WebAssembly.Module (wrangler's CompiledWasm rule)
import wasm from "../crate/pkg/executor_bg.wasm";

// Instantiated on the first request, not at module load (Workers' startup limit).
let ready = false;
function session(requestJson: string): WasmSession {
  if (!ready) {
    initSync({ module: wasm as WebAssembly.Module });
    ready = true;
  }
  return new Session(requestJson) as WasmSession;
}

export class Executor extends WorkerEntrypoint implements ExecutorApi {
  async execute(request: ExecRequest, state: StateSource): Promise<ExecResponse> {
    if (!EXECUTOR_METHODS.has(request?.method)) return { error: { code: -32601, message: `the method ${request?.method} does not exist/is not available` } };
    try {
      return await execute(request, state, session);
    } catch (e) {
      console.error("executor failed", e instanceof Error ? e.message : String(e));
      // A trap (Rust panic) leaves the instance unusable: the next request instantiates anew.
      if (e instanceof WebAssembly.RuntimeError) {
        __nullrpc_reset();
        ready = false;
      }
      return { error: { code: -32000, message: "execution failed" } };
    }
  }
}

export default {
  async fetch(): Promise<Response> {
    return new Response("Not found", { status: 404 });
  },
} satisfies ExportedHandler;
