// The executor as a Worker runs it: the WebAssembly (crate/pkg, built by scripts/build.sh and
// bundled by wrangler's CompiledWasm rule) behind the round loop (shell.ts). The RPC Worker
// (apps/rpc) calls `execute` in-process; the executor Worker (apps/executor) exposes the same
// function over a service binding.

import type { ExecRequest, ExecResponse, ExecutorApi, StateSource } from "./contract";
import { EXECUTOR_METHODS } from "./contract";
import { execute as run, type WasmSession } from "./shell";
// Generated by scripts/build.sh (part of every deploy script that bundles this package).
// @ts-ignore -- generated JavaScript without type declarations
import { __nullrpc_reset, initSync, Session } from "../crate/pkg/executor.js";
// @ts-ignore -- a compiled WebAssembly.Module (wrangler's CompiledWasm rule; test/wasm-node.ts under Node)
import wasm from "../crate/pkg/executor_bg.wasm";

export type { ExecRequest, ExecResponse, ExecutorApi, Hints, StateKey, StateSource, StateValue, Witness } from "./contract";
export { EXECUTOR_METHODS } from "./contract";

// Instantiated on the first request, not at module load (Workers' startup limit). One instance
// per isolate serves every request: sessions are independent and a round is synchronous, so
// requests interleave only between rounds.
let ready = false;
let inFlight = 0;
let trapped = false;

function session(requestJson: string): WasmSession {
  if (!ready) {
    initSync({ module: wasm as WebAssembly.Module });
    ready = true;
  }
  return new Session(requestJson) as WasmSession;
}

/** Runs one request to its JSON-RPC result or error, reading state through `state`. */
export async function execute(request: ExecRequest, state: StateSource): Promise<ExecResponse> {
  if (!EXECUTOR_METHODS.has(request?.method)) return { error: { code: -32601, message: `the method ${request?.method} does not exist/is not available` } };
  inFlight++;
  try {
    return await run(request, state, session);
  } catch (e) {
    console.error("executor failed", e instanceof Error ? e.message : String(e));
    // A trap (Rust panic) leaves the instance suspect: once no request is using it any more, it
    // is dropped and the next request instantiates anew (resetting under a running session
    // would leave that session with pointers into a memory that no longer exists).
    if (e instanceof WebAssembly.RuntimeError) trapped = true;
    return { error: { code: -32000, message: "execution failed" } };
  } finally {
    if (--inFlight === 0 && trapped) {
      __nullrpc_reset();
      ready = false;
      trapped = false;
    }
  }
}

/** `execute` as the RPC Worker's methods take it (apps/rpc, MethodEnv.executor). */
export const executor: ExecutorApi = { execute };
